<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('countries')->delete();
        $countries =[
			[
			  'id'=>1,
			  'sort'=>'AF',
			  'name'=>'Afghanistan',
              'is_active'=>'N',
			  'phoneCode'=>93
			],
			[
			  'id'=>2,
			  'sort'=>'AL',
			  'name'=>'Albania',
              'is_active'=>'N',
			  'phoneCode'=>355
			],
			[
			  'id'=>3,
			  'sort'=>'DZ',
			  'name'=>'Algeria',
              'is_active'=>'N',
			  'phoneCode'=>213
			    ],
			[
			  'id'=>4,
			  'sort'=>'AS',
			  'name'=>'American Samoa',
              'is_active'=>'N',
			  'phoneCode'=>1684
			    ],
			[
			  'id'=>5,
			  'sort'=>'AD',
			  'name'=>'Andorra',
              'is_active'=>'N',
			  'phoneCode'=>376
			    ],
			[
			  'id'=>6,
			  'sort'=>'AO',
			  'name'=>'Angola',
              'is_active'=>'N',
			  'phoneCode'=>244
			    ],
			[
			  'id'=>7,
			  'sort'=>'AI',
			  'name'=>'Anguilla',
              'is_active'=>'N',
			  'phoneCode'=>1264
			    ],
			[
			  'id'=>8,
			  'sort'=>'AQ',
			  'name'=>'Antarctica',
              'is_active'=>'N',
			  'phoneCode'=>0
			    ],
			[
			  'id'=>9,
			  'sort'=>'AG',
			  'name'=>'Antigua And Barbuda',
              'is_active'=>'N',
			  'phoneCode'=>1268
			    ],
			[
			  'id'=>10,
			  'sort'=>'AR',
			  'name'=>'Argentina',
              'is_active'=>'N',
			  'phoneCode'=>54
			    ],
			[
			  'id'=>11,
			  'sort'=>'AM',
			  'name'=>'Armenia',
              'is_active'=>'N',
			  'phoneCode'=>374
			    ],
			[
			  'id'=>12,
			  'sort'=>'AW',
			  'name'=>'Aruba',
              'is_active'=>'N',
			  'phoneCode'=>297
			    ],
			[
			  'id'=>13,
			  'sort'=>'AU',
			  'name'=>'Australia',
              'is_active'=>'N',
			  'phoneCode'=>61
			    ],
			[
			  'id'=>14,
			  'sort'=>'AT',
			  'name'=>'Austria',
              'is_active'=>'N',
			  'phoneCode'=>43
			    ],
			[
			  'id'=>15,
			  'sort'=>'AZ',
			  'name'=>'Azerbaijan',
              'is_active'=>'N',
			  'phoneCode'=>994
			    ],
			[
			  'id'=>16,
			  'sort'=>'BS',
			  'name'=>'Bahamas The',
              'is_active'=>'N',
			  'phoneCode'=>1242
			    ],
			[
			  'id'=>17,
			  'sort'=>'BH',
			  'name'=>'Bahrain',
              'is_active'=>'N',
			  'phoneCode'=>973
			    ],
			[
			  'id'=>18,
			  'sort'=>'BD',
			  'name'=>'Bangladesh',
              'is_active'=>'N',
			  'phoneCode'=>880
			    ],
			[
			  'id'=>19,
			  'sort'=>'BB',
			  'name'=>'Barbados',
              'is_active'=>'N',
			  'phoneCode'=>1246
			    ],
			[
			  'id'=>20,
			  'sort'=>'BY',
			  'name'=>'Belarus',
              'is_active'=>'N',
			  'phoneCode'=>375
			    ],
			[
			  'id'=>21,
			  'sort'=>'BE',
			  'name'=>'Belgium',
              'is_active'=>'N',
			  'phoneCode'=>32
			    ],
			[
			  'id'=>22,
			  'sort'=>'BZ',
			  'name'=>'Belize',
              'is_active'=>'N',
			  'phoneCode'=>501
			    ],
			[
			  'id'=>23,
			  'sort'=>'BJ',
			  'name'=>'Benin',
              'is_active'=>'N',
			  'phoneCode'=>229
			    ],
			[
			  'id'=>24,
			  'sort'=>'BM',
			  'name'=>'Bermuda',
              'is_active'=>'N',
			  'phoneCode'=>1441
			    ],
			[
			  'id'=>25,
			  'sort'=>'BT',
			  'name'=>'Bhutan',
              'is_active'=>'N',
			  'phoneCode'=>975
			    ],
			[
			  'id'=>26,
			  'sort'=>'BO',
			  'name'=>'Bolivia',
              'is_active'=>'N',
			  'phoneCode'=>591
			    ],
			[
			  'id'=>27,
			  'sort'=>'BA',
			  'name'=>'Bosnia and Herzegovina',
              'is_active'=>'N',
			  'phoneCode'=>387
			    ],
			[
			  'id'=>28,
			  'sort'=>'BW',
			  'name'=>'Botswana',
              'is_active'=>'N',
			  'phoneCode'=>267
			    ],
			[
			  'id'=>29,
			  'sort'=>'BV',
			  'name'=>'Bouvet Island',
              'is_active'=>'N',
			  'phoneCode'=>0
			    ],
			[
			  'id'=>30,
			  'sort'=>'BR',
			  'name'=>'Brazil',
              'is_active'=>'N',
			  'phoneCode'=>55
			    ],
			[
			  'id'=>31,
			  'sort'=>'IO',
			  'name'=>'British Indian Ocean Territory',
              'is_active'=>'N',
			  'phoneCode'=>246
			    ],
			[
			  'id'=>32,
			  'sort'=>'BN',
			  'name'=>'Brunei',
              'is_active'=>'N',
			  'phoneCode'=>673
			    ],
			[
			  'id'=>33,
			  'sort'=>'BG',
			  'name'=>'Bulgaria',
              'is_active'=>'N',
			  'phoneCode'=>359
			    ],
			[
			  'id'=>34,
			  'sort'=>'BF',
			  'name'=>'Burkina Faso',
              'is_active'=>'N',
			  'phoneCode'=>226
			    ],
			[
			  'id'=>35,
			  'sort'=>'BI',
			  'name'=>'Burundi',
              'is_active'=>'N',
			  'phoneCode'=>257
			    ],
			[
			  'id'=>36,
			  'sort'=>'KH',
			  'name'=>'Cambodia',
              'is_active'=>'N',
			  'phoneCode'=>855
			    ],
			[
			  'id'=>37,
			  'sort'=>'CM',
			  'name'=>'Cameroon',
              'is_active'=>'N',
			  'phoneCode'=>237
			    ],
			[
			  'id'=>38,
			  'sort'=>'CA',
			  'name'=>'Canada',
              'is_active'=>'N',
			  'phoneCode'=>1
			    ],
			[
			  'id'=>39,
			  'sort'=>'CV',
			  'name'=>'Cape Verde',
              'is_active'=>'N',
			  'phoneCode'=>238
			    ],
			[
			  'id'=>40,
			  'sort'=>'KY',
			  'name'=>'Cayman Islands',
              'is_active'=>'N',
			  'phoneCode'=>1345
			    ],
			[
			  'id'=>41,
			  'sort'=>'CF',
			  'name'=>'Central African Republic',
              'is_active'=>'N',
			  'phoneCode'=>236
			    ],
			[
			  'id'=>42,
			  'sort'=>'TD',
			  'name'=>'Chad',
              'is_active'=>'N',
			  'phoneCode'=>235
			    ],
			[
			  'id'=>43,
			  'sort'=>'CL',
			  'name'=>'Chile',
              'is_active'=>'N',
			  'phoneCode'=>56
			    ],
			[
			  'id'=>44,
			  'sort'=>'CN',
			  'name'=>'China',
              'is_active'=>'N',
			  'phoneCode'=>86
			    ],
			[
			  'id'=>45,
			  'sort'=>'CX',
			  'name'=>'Christmas Island',
              'is_active'=>'N',
			  'phoneCode'=>61
			    ],
			[
			  'id'=>46,
			  'sort'=>'CC',
			  'name'=>'Cocos (Keeling) Islands',
              'is_active'=>'N',
			  'phoneCode'=>672
			    ],
			[
			  'id'=>47,
			  'sort'=>'CO',
			  'name'=>'Colombia',
              'is_active'=>'N',
			  'phoneCode'=>57
			    ],
			[
			  'id'=>48,
			  'sort'=>'KM',
			  'name'=>'Comoros',
              'is_active'=>'N',
			  'phoneCode'=>269
			    ],
			[
			  'id'=>49,
			  'sort'=>'CG',
			  'name'=>'Republic Of The Congo',
              'is_active'=>'N',
			  'phoneCode'=>242
			    ],
			[
			  'id'=>50,
			  'sort'=>'CD',
			  'name'=>'Democratic Republic Of The Congo',
              'is_active'=>'N',
			  'phoneCode'=>242
			    ],
			[
			  'id'=>51,
			  'sort'=>'CK',
			  'name'=>'Cook Islands',
              'is_active'=>'N',
			  'phoneCode'=>682
			    ],
			[
			  'id'=>52,
			  'sort'=>'CR',
			  'name'=>'Costa Rica',
              'is_active'=>'N',
			  'phoneCode'=>506
			    ],
			[
			  'id'=>53,
			  'sort'=>'CI',
			  'name'=>'Cote D Ivoire (Ivory Coast)',
              'is_active'=>'N',
			  'phoneCode'=>225
			    ],
			[
			  'id'=>54,
			  'sort'=>'HR',
			  'name'=>'Croatia (Hrvatska)',
              'is_active'=>'N',
			  'phoneCode'=>385
			    ],
			[
			  'id'=>55,
			  'sort'=>'CU',
			  'name'=>'Cuba',
              'is_active'=>'N',
			  'phoneCode'=>53
			    ],
			[
			  'id'=>56,
			  'sort'=>'CY',
			  'name'=>'Cyprus',
              'is_active'=>'N',
			  'phoneCode'=>357
			    ],
			[
			  'id'=>57,
			  'sort'=>'CZ',
			  'name'=>'Czech Republic',
              'is_active'=>'N',
			  'phoneCode'=>420
			    ],
			[
			  'id'=>58,
			  'sort'=>'DK',
			  'name'=>'Denmark',
              'is_active'=>'N',
			  'phoneCode'=>45
			    ],
			[
			  'id'=>59,
			  'sort'=>'DJ',
			  'name'=>'Djibouti',
              'is_active'=>'N',
			  'phoneCode'=>253
			    ],
			[
			  'id'=>60,
			  'sort'=>'DM',
			  'name'=>'Dominica',
              'is_active'=>'N',
			  'phoneCode'=>1767
			    ],
			[
			  'id'=>61,
			  'sort'=>'DO',
			  'name'=>'Dominican Republic',
              'is_active'=>'N',
			  'phoneCode'=>1809
			    ],
			[
			  'id'=>62,
			  'sort'=>'TP',
			  'name'=>'East Timor',
              'is_active'=>'N',
			  'phoneCode'=>670
			    ],
			[
			  'id'=>63,
			  'sort'=>'EC',
			  'name'=>'Ecuador',
              'is_active'=>'N',
			  'phoneCode'=>593
			    ],
			[
			  'id'=>64,
			  'sort'=>'EG',
			  'name'=>'Egypt',
              'is_active'=>'N',
			  'phoneCode'=>20
			    ],
			[
			  'id'=>65,
			  'sort'=>'SV',
			  'name'=>'El Salvador',
              'is_active'=>'N',
			  'phoneCode'=>503
			    ],
			[
			  'id'=>66,
			  'sort'=>'GQ',
			  'name'=>'Equatorial Guinea',
              'is_active'=>'N',
			  'phoneCode'=>240
			    ],
			[
			  'id'=>67,
			  'sort'=>'ER',
			  'name'=>'Eritrea',
              'is_active'=>'N',
			  'phoneCode'=>291
			    ],
			[
			  'id'=>68,
			  'sort'=>'EE',
			  'name'=>'Estonia',
              'is_active'=>'N',
			  'phoneCode'=>372
			    ],
			[
			  'id'=>69,
			  'sort'=>'ET',
			  'name'=>'Ethiopia',
              'is_active'=>'N',
			  'phoneCode'=>251
			    ],
			[
			  'id'=>70,
			  'sort'=>'XA',
			  'name'=>'External Territories of Australia',
              'is_active'=>'N',
			  'phoneCode'=>61
			    ],
			[
			  'id'=>71,
			  'sort'=>'FK',
			  'name'=>'Falkland Islands',
              'is_active'=>'N',
			  'phoneCode'=>500
			    ],
			[
			  'id'=>72,
			  'sort'=>'FO',
			  'name'=>'Faroe Islands',
              'is_active'=>'N',
			  'phoneCode'=>298
			    ],
			[
			  'id'=>73,
			  'sort'=>'FJ',
			  'name'=>'Fiji Islands',
              'is_active'=>'N',
			  'phoneCode'=>679
			    ],
			[
			  'id'=>74,
			  'sort'=>'FI',
			  'name'=>'Finland',
              'is_active'=>'N',
			  'phoneCode'=>358
			    ],
			[
			  'id'=>75,
			  'sort'=>'FR',
			  'name'=>'France',
              'is_active'=>'N',
			  'phoneCode'=>33
			    ],
			[
			  'id'=>76,
			  'sort'=>'GF',
			  'name'=>'French Guiana',
              'is_active'=>'N',
			  'phoneCode'=>594
			    ],
			[
			  'id'=>77,
			  'sort'=>'PF',
			  'name'=>'French Polynesia',
              'is_active'=>'N',
			  'phoneCode'=>689
			    ],
			[
			  'id'=>78,
			  'sort'=>'TF',
			  'name'=>'French Southern Territories',
              'is_active'=>'N',
			  'phoneCode'=>0
			    ],
			[
			  'id'=>79,
			  'sort'=>'GA',
			  'name'=>'Gabon',
              'is_active'=>'N',
			  'phoneCode'=>241
			    ],
			[
			  'id'=>80,
			  'sort'=>'GM',
			  'name'=>'Gambia The',
              'is_active'=>'N',
			  'phoneCode'=>220
			    ],
			[
			  'id'=>81,
			  'sort'=>'GE',
			  'name'=>'Georgia',
              'is_active'=>'N',
			  'phoneCode'=>995
			    ],
			[
			  'id'=>82,
			  'sort'=>'DE',
			  'name'=>'Germany',
              'is_active'=>'N',
			  'phoneCode'=>49
			    ],
			[
			  'id'=>83,
			  'sort'=>'GH',
			  'name'=>'Ghana',
              'is_active'=>'N',
			  'phoneCode'=>233
			    ],
			[
			  'id'=>84,
			  'sort'=>'GI',
			  'name'=>'Gibraltar',
              'is_active'=>'N',
			  'phoneCode'=>350
			    ],
			[
			  'id'=>85,
			  'sort'=>'GR',
			  'name'=>'Greece',
              'is_active'=>'N',
			  'phoneCode'=>30
			    ],
			[
			  'id'=>86,
			  'sort'=>'GL',
			  'name'=>'Greenland',
              'is_active'=>'N',
			  'phoneCode'=>299
			    ],
			[
			  'id'=>87,
			  'sort'=>'GD',
			  'name'=>'Grenada',
              'is_active'=>'N',
			  'phoneCode'=>1473
			    ],
			[
			  'id'=>88,
			  'sort'=>'GP',
			  'name'=>'Guadeloupe',
              'is_active'=>'N',
			  'phoneCode'=>590
			    ],
			[
			  'id'=>89,
			  'sort'=>'GU',
			  'name'=>'Guam',
              'is_active'=>'N',
			  'phoneCode'=>1671
			    ],
			[
			  'id'=>90,
			  'sort'=>'GT',
			  'name'=>'Guatemala',
              'is_active'=>'N',
			  'phoneCode'=>502
			    ],
			[
			  'id'=>91,
			  'sort'=>'XU',
			  'name'=>'Guernsey and Alderney',
              'is_active'=>'N',
			  'phoneCode'=>44
			    ],
			[
			  'id'=>92,
			  'sort'=>'GN',
			  'name'=>'Guinea',
              'is_active'=>'N',
			  'phoneCode'=>224
			    ],
			[
			  'id'=>93,
			  'sort'=>'GW',
			  'name'=>'Guinea-Bissau',
              'is_active'=>'N',
			  'phoneCode'=>245
			    ],
			[
			  'id'=>94,
			  'sort'=>'GY',
			  'name'=>'Guyana',
              'is_active'=>'N',
			  'phoneCode'=>592
			    ],
			[
			  'id'=>95,
			  'sort'=>'HT',
			  'name'=>'Haiti',
              'is_active'=>'N',
			  'phoneCode'=>509
			    ],
			[
			  'id'=>96,
			  'sort'=>'HM',
			  'name'=>'Heard and McDonald Islands',
              'is_active'=>'N',
			  'phoneCode'=>0
			    ],
			[
			  'id'=>97,
			  'sort'=>'HN',
			  'name'=>'Honduras',
              'is_active'=>'N',
			  'phoneCode'=>504
			    ],
			[
			  'id'=>98,
			  'sort'=>'HK',
			  'name'=>'Hong Kong S.A.R.',
              'is_active'=>'N',
			  'phoneCode'=>852
			    ],
			[
			  'id'=>99,
			  'sort'=>'HU',
			  'name'=>'Hungary',
              'is_active'=>'N',
			  'phoneCode'=>36
			    ],
			[
			  'id'=>100,
			  'sort'=>'IS',
			  'name'=>'Iceland',
              'is_active'=>'N',
			  'phoneCode'=>354
			    ],
			[
			  'id'=>101,
			  'sort'=>'IN',
			  'name'=>'India',
              'is_active'=>'Y',
			  'phoneCode'=>91
			    ],
			[
			  'id'=>102,
			  'sort'=>'id',
			  'name'=>'Indonesia',
              'is_active'=>'N',
			  'phoneCode'=>62
			    ],
			[
			  'id'=>103,
			  'sort'=>'IR',
			  'name'=>'Iran',
              'is_active'=>'N',
			  'phoneCode'=>98
			    ],
			[
			  'id'=>104,
			  'sort'=>'IQ',
			  'name'=>'Iraq',
              'is_active'=>'N',
			  'phoneCode'=>964
			    ],
			[
			  'id'=>105,
			  'sort'=>'IE',
			  'name'=>'Ireland',
              'is_active'=>'N',
			  'phoneCode'=>353
			    ],
			[
			  'id'=>106,
			  'sort'=>'IL',
			  'name'=>'Israel',
              'is_active'=>'N',
			  'phoneCode'=>972
			    ],
			[
			  'id'=>107,
			  'sort'=>'IT',
			  'name'=>'Italy',
              'is_active'=>'N',
			  'phoneCode'=>39
			    ],
			[
			  'id'=>108,
			  'sort'=>'JM',
			  'name'=>'Jamaica',
              'is_active'=>'N',
			  'phoneCode'=>1876
			    ],
			[
			  'id'=>109,
			  'sort'=>'JP',
			  'name'=>'Japan',
              'is_active'=>'N',
			  'phoneCode'=>81
			    ],
			[
			  'id'=>110,
			  'sort'=>'XJ',
			  'name'=>'Jersey',
              'is_active'=>'N',
			  'phoneCode'=>44
			    ],
			[
			  'id'=>111,
			  'sort'=>'JO',
			  'name'=>'Jordan',
              'is_active'=>'N',
			  'phoneCode'=>962
			    ],
			[
			  'id'=>112,
			  'sort'=>'KZ',
			  'name'=>'Kazakhstan',
              'is_active'=>'N',
			  'phoneCode'=>7
			    ],
			[
			  'id'=>113,
			  'sort'=>'KE',
			  'name'=>'Kenya',
              'is_active'=>'N',
			  'phoneCode'=>254
			    ],
			[
			  'id'=>114,
			  'sort'=>'KI',
			  'name'=>'Kiribati',
              'is_active'=>'N',
			  'phoneCode'=>686
			    ],
			[
			  'id'=>115,
			  'sort'=>'KP',
			  'name'=>'Korea North',
              'is_active'=>'N',
			  'phoneCode'=>850
			    ],
			[
			  'id'=>116,
			  'sort'=>'KR',
			  'name'=>'Korea South',
              'is_active'=>'N',
			  'phoneCode'=>82
			    ],
			[
			  'id'=>117,
			  'sort'=>'KW',
			  'name'=>'Kuwait',
              'is_active'=>'N',
			  'phoneCode'=>965
			    ],
			[
			  'id'=>118,
			  'sort'=>'KG',
			  'name'=>'Kyrgyzstan',
              'is_active'=>'N',
			  'phoneCode'=>996
			    ],
			[
			  'id'=>119,
			  'sort'=>'LA',
			  'name'=>'Laos',
              'is_active'=>'N',
			  'phoneCode'=>856
			    ],
			[
			  'id'=>120,
			  'sort'=>'LV',
			  'name'=>'Latvia',
              'is_active'=>'N',
			  'phoneCode'=>371
			    ],
			[
			  'id'=>121,
			  'sort'=>'LB',
			  'name'=>'Lebanon',
              'is_active'=>'N',
			  'phoneCode'=>961
			    ],
			[
			  'id'=>122,
			  'sort'=>'LS',
			  'name'=>'Lesotho',
              'is_active'=>'N',
			  'phoneCode'=>266
			    ],
			[
			  'id'=>123,
			  'sort'=>'LR',
			  'name'=>'Liberia',
              'is_active'=>'N',
			  'phoneCode'=>231
			    ],
			[
			  'id'=>124,
			  'sort'=>'LY',
			  'name'=>'Libya',
              'is_active'=>'N',
			  'phoneCode'=>218
			    ],
			[
			  'id'=>125,
			  'sort'=>'LI',
			  'name'=>'Liechtenstein',
              'is_active'=>'N',
			  'phoneCode'=>423
			    ],
			[
			  'id'=>126,
			  'sort'=>'LT',
			  'name'=>'Lithuania',
              'is_active'=>'N',
			  'phoneCode'=>370
			    ],
			[
			  'id'=>127,
			  'sort'=>'LU',
			  'name'=>'Luxembourg',
              'is_active'=>'N',
			  'phoneCode'=>352
			    ],
			[
			  'id'=>128,
			  'sort'=>'MO',
			  'name'=>'Macau S.A.R.',
              'is_active'=>'N',
			  'phoneCode'=>853
			    ],
			[
			  'id'=>129,
			  'sort'=>'MK',
			  'name'=>'Macedonia',
              'is_active'=>'N',
			  'phoneCode'=>389
			    ],
			[
			  'id'=>130,
			  'sort'=>'MG',
			  'name'=>'Madagascar',
              'is_active'=>'N',
			  'phoneCode'=>261
			    ],
			[
			  'id'=>131,
			  'sort'=>'MW',
			  'name'=>'Malawi',
              'is_active'=>'N',
			  'phoneCode'=>265
			    ],
			[
			  'id'=>132,
			  'sort'=>'MY',
			  'name'=>'Malaysia',
              'is_active'=>'N',
			  'phoneCode'=>60
			    ],
			[
			  'id'=>133,
			  'sort'=>'MV',
			  'name'=>'Maldives',
              'is_active'=>'N',
			  'phoneCode'=>960
			    ],
			[
			  'id'=>134,
			  'sort'=>'ML',
			  'name'=>'Mali',
              'is_active'=>'N',
			  'phoneCode'=>223
			    ],
			[
			  'id'=>135,
			  'sort'=>'MT',
			  'name'=>'Malta',
              'is_active'=>'N',
			  'phoneCode'=>356
			    ],
			[
			  'id'=>136,
			  'sort'=>'XM',
			  'name'=>'Man (Isle of)',
              'is_active'=>'N',
			  'phoneCode'=>44
			    ],
			[
			  'id'=>137,
			  'sort'=>'MH',
			  'name'=>'Marshall Islands',
              'is_active'=>'N',
			  'phoneCode'=>692
			    ],
			[
			  'id'=>138,
			  'sort'=>'MQ',
			  'name'=>'Martinique',
              'is_active'=>'N',
			  'phoneCode'=>596
			    ],
			[
			  'id'=>139,
			  'sort'=>'MR',
			  'name'=>'Mauritania',
              'is_active'=>'N',
			  'phoneCode'=>222
			    ],
			[
			  'id'=>140,
			  'sort'=>'MU',
			  'name'=>'Mauritius',
              'is_active'=>'N',
			  'phoneCode'=>230
			    ],
			[
			  'id'=>141,
			  'sort'=>'YT',
			  'name'=>'Mayotte',
              'is_active'=>'N',
			  'phoneCode'=>269
			    ],
			[
			  'id'=>142,
			  'sort'=>'MX',
			  'name'=>'Mexico',
              'is_active'=>'N',
			  'phoneCode'=>52
			    ],
			[
			  'id'=>143,
			  'sort'=>'FM',
			  'name'=>'Micronesia',
              'is_active'=>'N',
			  'phoneCode'=>691
			    ],
			[
			  'id'=>144,
			  'sort'=>'MD',
			  'name'=>'Moldova',
              'is_active'=>'N',
			  'phoneCode'=>373
			    ],
			[
			  'id'=>145,
			  'sort'=>'MC',
			  'name'=>'Monaco',
              'is_active'=>'N',
			  'phoneCode'=>377
			    ],
			[
			  'id'=>146,
			  'sort'=>'MN',
			  'name'=>'Mongolia',
              'is_active'=>'N',
			  'phoneCode'=>976
			    ],
			[
			  'id'=>147,
			  'sort'=>'MS',
			  'name'=>'Montserrat',
              'is_active'=>'N',
			  'phoneCode'=>1664
			    ],
			[
			  'id'=>148,
			  'sort'=>'MA',
			  'name'=>'Morocco',
              'is_active'=>'N',
			  'phoneCode'=>212
			    ],
			[
			  'id'=>149,
			  'sort'=>'MZ',
			  'name'=>'Mozambique',
              'is_active'=>'N',
			  'phoneCode'=>258
			    ],
			[
			  'id'=>150,
			  'sort'=>'MM',
			  'name'=>'Myanmar',
              'is_active'=>'N',
			  'phoneCode'=>95
			    ],
			[
			  'id'=>151,
			  'sort'=>'NA',
			  'name'=>'Namibia',
              'is_active'=>'N',
			  'phoneCode'=>264
			    ],
			[
			  'id'=>152,
			  'sort'=>'NR',
			  'name'=>'Nauru',
              'is_active'=>'N',
			  'phoneCode'=>674
			    ],
			[
			  'id'=>153,
			  'sort'=>'NP',
			  'name'=>'Nepal',
              'is_active'=>'N',
			  'phoneCode'=>977
			    ],
			[
			  'id'=>154,
			  'sort'=>'AN',
			  'name'=>'Netherlands Antilles',
              'is_active'=>'N',
			  'phoneCode'=>599
			    ],
			[
			  'id'=>155,
			  'sort'=>'NL',
			  'name'=>'Netherlands The',
              'is_active'=>'N',
			  'phoneCode'=>31
			    ],
			[
			  'id'=>156,
			  'sort'=>'NC',
			  'name'=>'New Caledonia',
              'is_active'=>'N',
			  'phoneCode'=>687
			    ],
			[
			  'id'=>157,
			  'sort'=>'NZ',
			  'name'=>'New Zealand',
              'is_active'=>'N',
			  'phoneCode'=>64
			    ],
			[
			  'id'=>158,
			  'sort'=>'NI',
			  'name'=>'Nicaragua',
              'is_active'=>'N',
			  'phoneCode'=>505
			    ],
			[
			  'id'=>159,
			  'sort'=>'NE',
			  'name'=>'Niger',
              'is_active'=>'N',
			  'phoneCode'=>227
			    ],
			[
			  'id'=>160,
			  'sort'=>'NG',
			  'name'=>'Nigeria',
              'is_active'=>'N',
			  'phoneCode'=>234
			    ],
			[
			  'id'=>161,
			  'sort'=>'NU',
			  'name'=>'Niue',
              'is_active'=>'N',
			  'phoneCode'=>683
			    ],
			[
			  'id'=>162,
			  'sort'=>'NF',
			  'name'=>'Norfolk Island',
              'is_active'=>'N',
			  'phoneCode'=>672
			    ],
			[
			  'id'=>163,
			  'sort'=>'MP',
			  'name'=>'Northern Mariana Islands',
              'is_active'=>'N',
			  'phoneCode'=>1670
			    ],
			[
			  'id'=>164,
			  'sort'=>'NO',
			  'name'=>'Norway',
              'is_active'=>'N',
			  'phoneCode'=>47
			    ],
			[
			  'id'=>165,
			  'sort'=>'OM',
			  'name'=>'Oman',
              'is_active'=>'N',
			  'phoneCode'=>968
			    ],
			[
			  'id'=>166,
			  'sort'=>'PK',
			  'name'=>'Pakistan',
              'is_active'=>'N',
			  'phoneCode'=>92
			    ],
			[
			  'id'=>167,
			  'sort'=>'PW',
			  'name'=>'Palau',
              'is_active'=>'N',
			  'phoneCode'=>680
			    ],
			[
			  'id'=>168,
			  'sort'=>'PS',
			  'name'=>'Palestinian Territory Occupied',
              'is_active'=>'N',
			  'phoneCode'=>970
			    ],
			[
			  'id'=>169,
			  'sort'=>'PA',
			  'name'=>'Panama',
              'is_active'=>'N',
			  'phoneCode'=>507
			    ],
			[
			  'id'=>170,
			  'sort'=>'PG',
			  'name'=>'Papua new Guinea',
              'is_active'=>'N',
			  'phoneCode'=>675
			    ],
			[
			  'id'=>171,
			  'sort'=>'PY',
			  'name'=>'Paraguay',
              'is_active'=>'N',
			  'phoneCode'=>595
			    ],
			[
			  'id'=>172,
			  'sort'=>'PE',
			  'name'=>'Peru',
              'is_active'=>'N',
			  'phoneCode'=>51
			    ],
			[
			  'id'=>173,
			  'sort'=>'PH',
			  'name'=>'Philippines',
              'is_active'=>'N',
			  'phoneCode'=>63
			    ],
			[
			  'id'=>174,
			  'sort'=>'PN',
			  'name'=>'Pitcairn Island',
              'is_active'=>'N',
			  'phoneCode'=>0
			    ],
			[
			  'id'=>175,
			  'sort'=>'PL',
			  'name'=>'Poland',
              'is_active'=>'N',
			  'phoneCode'=>48
			    ],
			[
			  'id'=>176,
			  'sort'=>'PT',
			  'name'=>'Portugal',
              'is_active'=>'N',
			  'phoneCode'=>351
			    ],
			[
			  'id'=>177,
			  'sort'=>'PR',
			  'name'=>'Puerto Rico',
              'is_active'=>'N',
			  'phoneCode'=>1787
			    ],
			[
			  'id'=>178,
			  'sort'=>'QA',
			  'name'=>'Qatar',
              'is_active'=>'N',
			  'phoneCode'=>974
			    ],
			[
			  'id'=>179,
			  'sort'=>'RE',
			  'name'=>'Reunion',
              'is_active'=>'N',
			  'phoneCode'=>262
			    ],
			[
			  'id'=>180,
			  'sort'=>'RO',
			  'name'=>'Romania',
              'is_active'=>'N',
			  'phoneCode'=>40
			    ],
			[
			  'id'=>181,
			  'sort'=>'RU',
			  'name'=>'Russia',
              'is_active'=>'N',
			  'phoneCode'=>70
			    ],
			[
			  'id'=>182,
			  'sort'=>'RW',
			  'name'=>'Rwanda',
              'is_active'=>'N',
			  'phoneCode'=>250
			    ],
			[
			  'id'=>183,
			  'sort'=>'SH',
			  'name'=>'Saint Helena',
              'is_active'=>'N',
			  'phoneCode'=>290
			    ],
			[
			  'id'=>184,
			  'sort'=>'KN',
			  'name'=>'Saint Kitts And Nevis',
              'is_active'=>'N',
			  'phoneCode'=>1869
			    ],
			[
			  'id'=>185,
			  'sort'=>'LC',
			  'name'=>'Saint Lucia',
              'is_active'=>'N',
			  'phoneCode'=>1758
			    ],
			[
			  'id'=>186,
			  'sort'=>'PM',
			  'name'=>'Saint Pierre and Miquelon',
              'is_active'=>'N',
			  'phoneCode'=>508
			    ],
			[
			  'id'=>187,
			  'sort'=>'VC',
			  'name'=>'Saint Vincent And The Grenadines',
              'is_active'=>'N',
			  'phoneCode'=>1784
			    ],
			[
			  'id'=>188,
			  'sort'=>'WS',
			  'name'=>'Samoa',
              'is_active'=>'N',
			  'phoneCode'=>684
			    ],
			[
			  'id'=>189,
			  'sort'=>'SM',
			  'name'=>'San Marino',
              'is_active'=>'N',
			  'phoneCode'=>378
			    ],
			[
			  'id'=>190,
			  'sort'=>'ST',
			  'name'=>'Sao Tome and Principe',
              'is_active'=>'N',
			  'phoneCode'=>239
			    ],
			[
			  'id'=>191,
			  'sort'=>'SA',
			  'name'=>'Saudi Arabia',
              'is_active'=>'N',
			  'phoneCode'=>966
			    ],
			[
			  'id'=>192,
			  'sort'=>'SN',
			  'name'=>'Senegal',
              'is_active'=>'N',
			  'phoneCode'=>221
			    ],
			[
			  'id'=>193,
			  'sort'=>'RS',
			  'name'=>'Serbia',
              'is_active'=>'N',
			  'phoneCode'=>381
			    ],
			[
			  'id'=>194,
			  'sort'=>'SC',
			  'name'=>'Seychelles',
              'is_active'=>'N',
			  'phoneCode'=>248
			    ],
			[
			  'id'=>195,
			  'sort'=>'SL',
			  'name'=>'Sierra Leone',
              'is_active'=>'N',
			  'phoneCode'=>232
			    ],
			[
			  'id'=>196,
			  'sort'=>'SG',
			  'name'=>'Singapore',
              'is_active'=>'N',
			  'phoneCode'=>65
			    ],
			[
			  'id'=>197,
			  'sort'=>'SK',
			  'name'=>'Slovakia',
              'is_active'=>'N',
			  'phoneCode'=>421
			    ],
			[
			  'id'=>198,
			  'sort'=>'SI',
			  'name'=>'Slovenia',
              'is_active'=>'N',
			  'phoneCode'=>386
			    ],
			[
			  'id'=>199,
			  'sort'=>'XG',
			  'name'=>'Smaller Territories of the UK',
              'is_active'=>'N',
			  'phoneCode'=>44
			    ],
			[
			  'id'=>200,
			  'sort'=>'SB',
			  'name'=>'Solomon Islands',
              'is_active'=>'N',
			  'phoneCode'=>677
			    ],
			[
			  'id'=>201,
			  'sort'=>'SO',
			  'name'=>'Somalia',
              'is_active'=>'N',
			  'phoneCode'=>252
			    ],
			[
			  'id'=>202,
			  'sort'=>'ZA',
			  'name'=>'South Africa',
              'is_active'=>'N',
			  'phoneCode'=>27
			    ],
			[
			  'id'=>203,
			  'sort'=>'GS',
			  'name'=>'South Georgia',
              'is_active'=>'N',
			  'phoneCode'=>0
			    ],
			[
			  'id'=>204,
			  'sort'=>'SS',
			  'name'=>'South Sudan',
              'is_active'=>'N',
			  'phoneCode'=>211
			    ],
			[
			  'id'=>205,
			  'sort'=>'ES',
			  'name'=>'Spain',
              'is_active'=>'N',
			  'phoneCode'=>34
			    ],
			[
			  'id'=>206,
			  'sort'=>'LK',
			  'name'=>'Sri Lanka',
              'is_active'=>'N',
			  'phoneCode'=>94
			    ],
			[
			  'id'=>207,
			  'sort'=>'SD',
			  'name'=>'Sudan',
              'is_active'=>'N',
			  'phoneCode'=>249
			    ],
			[
			  'id'=>208,
			  'sort'=>'SR',
			  'name'=>'Suriname',
              'is_active'=>'N',
			  'phoneCode'=>597
			    ],
			[
			  'id'=>209,
			  'sort'=>'SJ',
			  'name'=>'Svalbard And Jan Mayen Islands',
              'is_active'=>'N',
			  'phoneCode'=>47
			    ],
			[
			  'id'=>210,
			  'sort'=>'SZ',
			  'name'=>'Swaziland',
              'is_active'=>'N',
			  'phoneCode'=>268
			    ],
			[
			  'id'=>211,
			  'sort'=>'SE',
			  'name'=>'Sweden',
              'is_active'=>'N',
			  'phoneCode'=>46
			    ],
			[
			  'id'=>212,
			  'sort'=>'CH',
			  'name'=>'Switzerland',
              'is_active'=>'N',
			  'phoneCode'=>41
			    ],
			[
			  'id'=>213,
			  'sort'=>'SY',
			  'name'=>'Syria',
              'is_active'=>'N',
			  'phoneCode'=>963
			    ],
			[
			  'id'=>214,
			  'sort'=>'TW',
			  'name'=>'Taiwan',
              'is_active'=>'N',
			  'phoneCode'=>886
			    ],
			[
			  'id'=>215,
			  'sort'=>'TJ',
			  'name'=>'Tajikistan',
              'is_active'=>'N',
			  'phoneCode'=>992
			    ],
			[
			  'id'=>216,
			  'sort'=>'TZ',
			  'name'=>'Tanzania',
              'is_active'=>'N',
			  'phoneCode'=>255
			    ],
			[
			  'id'=>217,
			  'sort'=>'TH',
			  'name'=>'Thailand',
              'is_active'=>'N',
			  'phoneCode'=>66
			    ],
			[
			  'id'=>218,
			  'sort'=>'TG',
			  'name'=>'Togo',
              'is_active'=>'N',
			  'phoneCode'=>228
			    ],
			[
			  'id'=>219,
			  'sort'=>'TK',
			  'name'=>'Tokelau',
              'is_active'=>'N',
			  'phoneCode'=>690
			    ],
			[
			  'id'=>220,
			  'sort'=>'TO',
			  'name'=>'Tonga',
              'is_active'=>'N',
			  'phoneCode'=>676
			    ],
			[
			  'id'=>221,
			  'sort'=>'TT',
			  'name'=>'Trinidad And Tobago',
              'is_active'=>'N',
			  'phoneCode'=>1868
			    ],
			[
			  'id'=>222,
			  'sort'=>'TN',
			  'name'=>'Tunisia',
              'is_active'=>'N',
			  'phoneCode'=>216
			    ],
			[
			  'id'=>223,
			  'sort'=>'TR',
			  'name'=>'Turkey',
              'is_active'=>'N',
			  'phoneCode'=>90
			    ],
			[
			  'id'=>224,
			  'sort'=>'TM',
			  'name'=>'Turkmenistan',
              'is_active'=>'N',
			  'phoneCode'=>7370
			    ],
			[
			  'id'=>225,
			  'sort'=>'TC',
			  'name'=>'Turks And Caicos Islands',
              'is_active'=>'N',
			  'phoneCode'=>1649
			    ],
			[
			  'id'=>226,
			  'sort'=>'TV',
			  'name'=>'Tuvalu',
              'is_active'=>'N',
			  'phoneCode'=>688
			    ],
			[
			  'id'=>227,
			  'sort'=>'UG',
			  'name'=>'Uganda',
              'is_active'=>'N',
			  'phoneCode'=>256
			    ],
			[
			  'id'=>228,
			  'sort'=>'UA',
			  'name'=>'Ukraine',
              'is_active'=>'N',
			  'phoneCode'=>380
			    ],
			[
			  'id'=>229,
			  'sort'=>'AE',
			  'name'=>'United Arab Emirates',
              'is_active'=>'N',
			  'phoneCode'=>971
			    ],
			[
			  'id'=>230,
			  'sort'=>'GB',
			  'name'=>'United Kingdom',
              'is_active'=>'N',
			  'phoneCode'=>44
			    ],
			[
			  'id'=>231,
			  'sort'=>'US',
			  'name'=>'United States',
              'is_active'=>'N',
			  'phoneCode'=>1
			    ],
			[
			  'id'=>232,
			  'sort'=>'UM',
			  'name'=>'United States Minor Outlying Islands',
              'is_active'=>'N',
			  'phoneCode'=>1
			    ],
			[
			  'id'=>233,
			  'sort'=>'UY',
			  'name'=>'Uruguay',
              'is_active'=>'N',
			  'phoneCode'=>598
			    ],
			[
			  'id'=>234,
			  'sort'=>'UZ',
			  'name'=>'Uzbekistan',
              'is_active'=>'N',
			  'phoneCode'=>998
			    ],
			[
			  'id'=>235,
			  'sort'=>'VU',
			  'name'=>'Vanuatu',
              'is_active'=>'N',
			  'phoneCode'=>678
			    ],
			[
			  'id'=>236,
			  'sort'=>'VA',
			  'name'=>'Vatican City State (Holy See)',
              'is_active'=>'N',
			  'phoneCode'=>39
			    ],
			[
			  'id'=>237,
			  'sort'=>'VE',
			  'name'=>'Venezuela',
              'is_active'=>'N',
			  'phoneCode'=>58
			    ],
			[
			  'id'=>238,
			  'sort'=>'VN',
			  'name'=>'Vietnam',
              'is_active'=>'N',
			  'phoneCode'=>84
			    ],
			[
			  'id'=>239,
			  'sort'=>'VG',
			  'name'=>'Virgin Islands (British)',
              'is_active'=>'N',
			  'phoneCode'=>1284
			    ],
			[
			  'id'=>240,
			  'sort'=>'VI',
			  'name'=>'Virgin Islands (US)',
              'is_active'=>'N',
			  'phoneCode'=>1340
			    ],
			[
			  'id'=>241,
			  'sort'=>'WF',
			  'name'=>'Wallis And Futuna Islands',
              'is_active'=>'N',
			  'phoneCode'=>681
			    ],
			[
			  'id'=>242,
			  'sort'=>'EH',
			  'name'=>'Western Sahara',
              'is_active'=>'N',
			  'phoneCode'=>212
			    ],
			[
			  'id'=>243,
			  'sort'=>'YE',
			  'name'=>'Yemen',
              'is_active'=>'N',
			  'phoneCode'=>967
			    ],
			[
			  'id'=>244,
			  'sort'=>'YU',
			  'name'=>'Yugoslavia',
              'is_active'=>'N',
			  'phoneCode'=>38
			    ],
			[
			  'id'=>245,
			  'sort'=>'ZM',
			  'name'=>'Zambia',
              'is_active'=>'N',
			  'phoneCode'=>260
			    ],
			[
			  'id'=>246,
			  'sort'=>'ZW',
			  'name'=>'Zimbabwe',
              'is_active'=>'N',
			  'phoneCode'=>26
			],
		];
		Country::insert($countries);
    }
}
